### ISSUE TITLE
an error is raised when launching the usage example

### ISSUE THREAD

**Issue by lorenzoferre** [youdie323323/enigma#3]
### Describe the bug

The error shows a missing module (@babel/core); however, I tried to install it, but then other modules appeared that also needed to be installed, and in the end, it still didn't work.
I created a file called `code.js`, copied the usage example into it, and then installed the package with `npm i enigma-vm`

### Expected Behaviour

the usage example that works

### Code

```JavaScript
import { obfuscate } from "enigma-vm";

(async function () {
    const input = `
      function sayHello(name) {
          console.log("Hello,", name + "!");
      }

      for (let i = 0; i < 3; i++) {
          sayHello("Me and " + i);
      }
    `;

     const obfuscatedInput = await obfuscate(input);

    console.log(obfuscatedInput);
})();
```

### Logs

```Text
node:internal/modules/cjs/loader:1405
  const err = new Error(message);
              ^

Error: Cannot find module '@babel/core'
Require stack:
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/index.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Compiler.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/index.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Function._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1734:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/index.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Compiler.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/index.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/index.js'
  ]
}

Node.js v23.9.0
```

**Comment by youdie323323** [comment]
Sorry, that was my mistake. i accidentally included @babel/code as a dev dependency, i just published a new version. let me know if this fixes the issue

**Comment by lorenzoferre** [comment]
thank you for your immediate response. However, it seems it doesn't fix the problem completely (I don't know if I'm doing something wrong).
Now, another error appears:
```
node:internal/modules/cjs/loader:1405
  const err = new Error(message);
              ^

Error: Cannot find module 'unraw'
Require stack:
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Interpreter/Builder/InterpreterBuilder.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Interpreter/Builder/index.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Function._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Interpreter/Builder/InterpreterBuilder.js:15:37)
    at Module._compile (node:internal/modules/cjs/loader:1734:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Interpreter/Builder/InterpreterBuilder.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Interpreter/Builder/index.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/index.js'
  ]
}

Node.js v23.9.0
```
I tried to install the unraw package with `npm i unraw`, but then it appeared:
```
node:internal/modules/cjs/loader:1405
  const err = new Error(message);
              ^

Error: Cannot find module '@babel/plugin-transform-property-mutators'
Require stack:
- /root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/plugins.js
- /root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/index.js
- /root/vm-js/test-enigma/node_modules/@babel/core/lib/index.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/index.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Compiler.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/index.js
- /root/vm-js/test-enigma/node_modules/enigma-vm/Dist/index.js

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at resolve (node:internal/modules/helpers:145:19)
    at tryRequireResolve (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/plugins.js:128:11)
    at resolveStandardizedNameForRequire (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/plugins.js:162:19)
    at resolveStandardizedName (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/plugins.js:183:12)
    at loadPlugin (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/plugins.js:56:7)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at evaluateSync (/root/vm-js/test-enigma/node_modules/gensync/index.js:251:28)
    at /root/vm-js/test-enigma/node_modules/gensync/index.js:31:34
    at Array.map (<anonymous>)
    at Function.sync (/root/vm-js/test-enigma/node_modules/gensync/index.js:31:22)
    at Function.all (/root/vm-js/test-enigma/node_modules/gensync/index.js:210:24)
    at Generator.next (<anonymous>)
    at createDescriptors (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at /root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-descriptors.js:65:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/root/vm-js/test-enigma/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/root/vm-js/test-enigma/node_modules/gensync/index.js:251:28)
    at Function.sync (/root/vm-js/test-enigma/node_modules/gensync/index.js:89:14)
    at sync (/root/vm-js/test-enigma/node_modules/@babel/core/lib/gensync-utils/async.js:61:25)
    at sync (/root/vm-js/test-enigma/node_modules/gensync/index.js:182:19)
    at onFirstPause (/root/vm-js/test-enigma/node_modules/gensync/index.js:210:24)
    at Generator.next (<anonymous>)
    at cachedFunction (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at mergeChainOpts (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at buildRootChain (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/config-chain.js:56:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/full.js:36:46)
    at loadFullConfig.next (<anonymous>)
    at transform (/root/vm-js/test-enigma/node_modules/@babel/core/lib/transform.js:20:44)
    at transform.next (<anonymous>)
    at evaluateSync (/root/vm-js/test-enigma/node_modules/gensync/index.js:251:28)
    at sync (/root/vm-js/test-enigma/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/root/vm-js/test-enigma/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at transformSync (/root/vm-js/test-enigma/node_modules/@babel/core/lib/transform.js:42:76)
    at transformCode (/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js:54:34)
    at Parser.parse (/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js:69:28)
    at Compiler.compile (/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Compiler.js:1357:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/plugins.js',
    '/root/vm-js/test-enigma/node_modules/@babel/core/lib/config/files/index.js',
    '/root/vm-js/test-enigma/node_modules/@babel/core/lib/index.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/Parser.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Parser/index.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/Compiler.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/Compiler/index.js',
    '/root/vm-js/test-enigma/node_modules/enigma-vm/Dist/index.js'
  ]
}

Node.js v23.9.0
```
For completeness, here is the `package.json`:
```js
{
   "type": "module",
   "dependencies": {
    "enigma-vm": "^1.0.8",
    "unraw": "^3.0.0"
  }
}
```

**Comment by youdie323323** [comment]
Im sorry for the repeated trouble. The issue was that my user folder contained dependencies required for the project, but they were not installed in the project itself. I have released a new version, let me know if issue was fixed
